### PR TITLE
make awx/tower compatible

### PR DESCRIPTION
**Pull request by Phill93**

### CODE REVIEW

**Comment by a-delannoy** [comment]
Hi, and thank you for your interest in this project.
I'm glad to see a new MR !
First, I'd like to ask you why you want the script to be ran by python2 ? Is it for awx/tower compatibility ?
Secondly, you added this lines :
```
    try:
        if os.environ['netbox']:
            configuration = {'netbox': yaml.safe_load(os.environ['netbox'])}
        else:
            configuration = load_config_file(args.config_file)
    except KeyError:
        configuration = load_config_file(args.config_file)
```
I would suggest turning into :
```
        if os.environ.get('netbox', None):
            configuration = {'netbox': yaml.safe_load(os.environ['netbox'])}
        else:
            configuration = load_config_file(args.config_file)
```

**Comment by Phill93** [comment]
Hi,
awx has a problem with argparse and enum under python 3. Thats the reason I use python 2.
```
"/tmp/awx_13_xseayist/tmpydylt_jy", line 5, in <module>     import argparse
File "/usr/lib64/python3.6/argparse.py", line 89, in <module>     import re as _re
File "/usr/lib64/python3.6/re.py", line 142, in <module>     class RegexFlag(enum.IntFlag): AttributeError: module 'enum' has no attribute 'IntFlag'
```


> I would suggest turning into :
> 
>         if os.environ.get('netbox', None):
>             configuration = {'netbox': yaml.safe_load(os.environ['netbox'])}
>         else:
>             configuration = load_config_file(args.config_file)

Good idea

**Comment by a-delannoy** [comment]
Concerning the last lines you just added, why do you need it as the environment variable access is already handled in the arg_parse section ?

**Comment by Phill93** [comment]
awx can only pass environment variables to a custom inventory source, no arguments

**Comment by a-delannoy** [comment]
Unfortunately, since python2 will no longer be supported by 2020, we won't downgrade the python version.

**Pull request closed without merging**
